@php
    $url = request()->getSchemeAndHttpHost();
    $current_url = url()->current();
    $parsedUrl = parse_url($url);
    $domainParts = explode('.', $parsedUrl['host']);
    $domain =
        $domainParts[count($domainParts) - 3] .
        '.' .
        $domainParts[count($domainParts) - 2] .
        '.' .
        $domainParts[count($domainParts) - 1];

    $header_logo = get_setting('header_logo');
@endphp

<!DOCTYPE html>
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Zo.Tc Preview</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="images/favicon.png" />
    <meta name="next-head-count" content="5" />
    <link rel="preload" href="{{ url('public/landing-pages/_next/static/css/25e2d5e4d00fc798.css') }}"
        as="style" />
    <link rel="stylesheet" href="{{ url('public/landing-pages/_next/static/css/25e2d5e4d00fc798.css') }}"
        data-n-g="" />
    <link rel="preload" href="{{ url('public/landing-pages/_next/static/css/4efbf50d3f0886f5.css') }}"
        as="style" />
    <link rel="stylesheet" href="{{ url('public/landing-pages/_next/static/css/4efbf50d3f0886f5.css') }}"
        data-n-p="" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>
    <div id="__next">
        <div class="Landing__3">
            <section class="Banner">
                <div class="container">
                    <section id="Menubar">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="MenubarContent" class="menubar_MenubarContent__zOkMY">
                                        <div id="LogoLeft" class="menubar_LogoLeft__BBcWc"><img loading="lazy"
                                                width="356" height="77" decoding="async" data-nimg="1"
                                                style="color:transparent"
                                                src="{{ url('public/landing-pages/_next/static/media/logo.af8eb286.svg') }}" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="BannerContent">
                                <div class="text">
                                    <h1>শত ভেজাল ভিড়ে একমাত্র আমরাই আপনাকে দিচ্ছি খাঁটি ফরমালীন মুক্ত আম</h1>
                                    <h3>বাজারে আমের দাম উঠা-নামা করতে পারে, <br /> তাই ফোন করে আমের দাম কনফার্ম হোন</h3>
                                    <a class="bg" href="{{ $current_url }}#placeAnOrder"> <svg
                                            stroke="currentColor" fill="currentColor" stroke-width="0"
                                            viewBox="0 0 1024 1024" height="1em" width="1em"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M922.9 701.9H327.4l29.9-60.9 496.8-.9c16.8 0 31.2-12 34.2-28.6l68.8-385.1c1.8-10.1-.9-20.5-7.5-28.4a34.99 34.99 0 0 0-26.6-12.5l-632-2.1-5.4-25.4c-3.4-16.2-18-28-34.6-28H96.5a35.3 35.3 0 1 0 0 70.6h125.9L246 312.8l58.1 281.3-74.8 122.1a34.96 34.96 0 0 0-3 36.8c6 11.9 18.1 19.4 31.5 19.4h62.8a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7h161.1a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7H923c19.4 0 35.3-15.8 35.3-35.3a35.42 35.42 0 0 0-35.4-35.2zM305.7 253l575.8 1.9-56.4 315.8-452.3.8L305.7 253zm96.9 612.7c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6zm325.1 0c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6z">
                                            </path>
                                        </svg> অর্ডার করুন</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="section_gaps"></div>
            <section class="About">
                <div class="AboutText_left"><img src="{{ url('public/landing-pages/images/landing-3/About_left.png') }}"
                        alt="" /></div>
                <div class="AboutText_right"><img
                        src="{{ url('public/landing-pages/images/landing-3/About_right.png') }}" alt="" /></div>
                <div class="container">
                    <div class="justify-content-md-center row">
                        <div class="col-lg-6">
                            <div class="AboutContent">
                                <div class="AboutLogo"><img
                                        src="{{ url('public/landing-pages/images/landing-3/about.svg') }}"
                                        alt="" />
                                    <div class="AboutOverlay">
                                        <h3>{{ $landingPage->product->name }}</h3>
                                        {{-- <h4>পূর্বের মূল্যঃ ১০৫০ টাকা</h4> --}}
                                        <h2>মূল্যঃ {{ $landingPage->product->unit_price }} টাকা</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="AboutText">
                                <h2>আমাদের এই আম কেন খাবেন?</h2>
                                <p>আমরা হলাম কেমিক্যাল মুক্ত, উৎকৃষ্ট মানের রকমারি আমের একটি জায়গা।আমরা বিশেষত রাজশাহীর
                                    আমাদের নিজেস্ব বাগানের উৎকৃষ্ট মানের সম্পূর্ণ কেমিক্যাল মুক্ত আম। আম খেতে ভালোবাসেন
                                    না, এমন মানুষ পাওয়া খুব কম আছে। আমাদের এই আম স্বাদে ও গন্ধে অতুলনীয় পাকা ও কাঁচা
                                    আমে রয়েছে অনেক পুষ্টিগুণ তা শরীরের জন্য ভালো। গ্রাহকরা ভাল অবিশ্বাস্যভাবে আশ্বস্ত
                                    হয়ে ১০০% আস্থার সাথে আমাদের থেকে কাঁচা বা পাকা আম ক্রয় করতে পারেন । আমরা পাইকারি
                                    বিক্রয় সেবাও দিয়ে থাকি। আমরা সরাসরি গ্রাহকদের হোম ডেলিভারী দিয়ে থাকি এবং গ্রাহকদের
                                    হাতে পৌছে দেয়ার চেষ্টা অব্যাহত আছে, আপনি ও নিয়ে দেখতে পারেন।</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="WhyUs">
                <div class="WhyUsImg"><img src="{{ url('public/landing-pages/images/landing-3/why_us.png') }}"
                        alt="" />
                    <div class="WhyOverlay">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12">
                                    <h2>আমের উপকারিতা ও পুষ্টিগুণ কি কি?</h2>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" />
                                        </div>
                                        <div class="text">
                                            <p>প্রাকৃতিক ফলে বিদ্যমান ক্যারোটিন গ্রহণ করলে সেগুলো ফুসফুস ও মুখের
                                                ক্যানসারের ঝুঁকি কমায়।</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" />
                                        </div>
                                        <div class="text">
                                            <p>তাজা আম পটাশিয়ামের ভালো কাজ করে যা মানবদেহের কোষ ও তরলের উপাদান, যা
                                                রক্তচাপ ও হৃৎস্পন্দন নিয়ন্ত্রণে রাখতে সাহায্য করে।</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" />
                                        </div>
                                        <div class="text">
                                            <p>ভিটামিন সি ও বিভিন্ন অ্যান্টি-অক্সিডেন্ট পাওয়া যায়, যা দেহের রোগ
                                                প্রতিরোধক্ষমতা বৃদ্ধি করে।</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" /></div>
                                        <div class="text">
                                            <p>পাকা আম আমাদের ত্বক কে সুন্দর, উজ্জ্বল ও মসৃণ করে আম তারুণ্য ধরে রাখতে
                                                কার্যকর। </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" /></div>
                                        <div class="text">
                                            <p>গাছপাকা আমে পর্যাপ্ত পরিমাণে খনিজ লবণের উপস্থিতিও রয়েছে যা শরীরের দাঁত,
                                                নখ, চুল ইত্যাদি মজবুত করে।</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-sm-6">
                                    <div class="WhyUsItem">
                                        <div class="img"><img
                                                src="{{ url('public/landing-pages/images/landing-3/why_us_img.png') }}"
                                                alt="" /></div>
                                        <div class="text">
                                            <p>আমে থাকা বিভিন্ন উপাদান কোলেস্টেরলের ক্ষতিকর মাত্রা কমাতে সাহায্য করে
                                                হৃদ্‌রোগ ও স্ট্রোকের ঝুঁকি কমাতে কার্যকর।</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="section_gaps"></div>
            <section class="FreeDelivary">
                <div class="container">
                    <div class="d_flex row">
                        <div class="first_child col-lg-6">
                            <div class="FreeDelivaryText">
                                <ul>
                                    <li> <img src="{{ url('public/landing-pages/images/landing-3/tick.svg') }}"
                                            alt="" /> ঐতিহ্যবাহী রাজশাহীর
                                        আমাদের
                                        নিজেস্ব বাগানের আসল সেরা আম</li>
                                    <li> <img src="{{ url('public/landing-pages/images/landing-3/tick.svg') }}"
                                            alt="" /> কীটনাশক ও কেমিক্যাল
                                        মুক্ত আমের
                                        নির্ভরযোগ্য জায়গা</li>
                                    <li> <img src="{{ url('public/landing-pages/images/landing-3/tick.svg') }}"
                                            alt="" /> বাছাইকৃত বাগানের সেরা
                                        মানের
                                        সুস্বাধু আম</li>
                                    <li> <img src="{{ url('public/landing-pages/images/landing-3/tick.svg') }}"
                                            alt="" /> হাতের নিকটে ঘরে বসে
                                        পাচ্ছেন
                                        ভেজাল মুক্ত আম</li>
                                </ul>
                                <h3>সারাদেশে ফ্রি ডেলিভারি পেতে এখনি</h3><a class="bg"
                                    href="{{ $current_url }}#placeAnOrder"> <svg stroke="currentColor"
                                        fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em"
                                        width="1em" xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M922.9 701.9H327.4l29.9-60.9 496.8-.9c16.8 0 31.2-12 34.2-28.6l68.8-385.1c1.8-10.1-.9-20.5-7.5-28.4a34.99 34.99 0 0 0-26.6-12.5l-632-2.1-5.4-25.4c-3.4-16.2-18-28-34.6-28H96.5a35.3 35.3 0 1 0 0 70.6h125.9L246 312.8l58.1 281.3-74.8 122.1a34.96 34.96 0 0 0-3 36.8c6 11.9 18.1 19.4 31.5 19.4h62.8a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7h161.1a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7H923c19.4 0 35.3-15.8 35.3-35.3a35.42 35.42 0 0 0-35.4-35.2zM305.7 253l575.8 1.9-56.4 315.8-452.3.8L305.7 253zm96.9 612.7c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6zm325.1 0c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6z">
                                        </path>
                                    </svg> অর্ডার করুন</a>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="VideoPlay">
                                <div id="VideoPlayers" class="video_VideoPlayers__KZnPY"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="section_gaps"></div>
            <section class="Client">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="header text-center">
                                <h2>আমাদের মূল্যবান গ্রাহকদের <br /> মতামত গুলো জানুন</h2>
                            </div>
                        </div>
                    </div>
                    <div class="ClientContent">
                        <div class="row">
                            <div class="col-lg-6 col-sm-6">
                                <div class="ClientImg"><img
                                        src="{{ url('public/landing-pages/images/landing_2/client_review.html') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div class="ClientImg"><img
                                        src="{{ url('public/landing-pages/images/landing_2/client_review.html') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div class="ClientImg"><img
                                        src="{{ url('public/landing-pages/images/landing_2/client_review.html') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div class="ClientImg"><img
                                        src="{{ url('public/landing-pages/images/landing_2/client_review.html') }}"
                                        alt="" /></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="section_gaps"></div>
            <div class="section_gaps"></div>
            <section class="OrderNow">
                <div class="OrderLeft"><img src="{{ url('public/landing-pages/images/landing-3/order_left.png') }}"
                        alt="" /></div>
                <div class="OrderRight"><img src="{{ url('public/landing-pages/images/landing-3/order_right.png') }}"
                        alt="" /></div>
                <div class="container">
                    <div class="justify-content-md-center row">
                        <div class="col-lg-8">
                            <div class="OrderNowtext"><a class="bg" href="{{ $current_url }}#placeAnOrder">
                                    <svg stroke="currentColor" fill="currentColor" stroke-width="0"
                                        viewBox="0 0 1024 1024" height="1em" width="1em"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M922.9 701.9H327.4l29.9-60.9 496.8-.9c16.8 0 31.2-12 34.2-28.6l68.8-385.1c1.8-10.1-.9-20.5-7.5-28.4a34.99 34.99 0 0 0-26.6-12.5l-632-2.1-5.4-25.4c-3.4-16.2-18-28-34.6-28H96.5a35.3 35.3 0 1 0 0 70.6h125.9L246 312.8l58.1 281.3-74.8 122.1a34.96 34.96 0 0 0-3 36.8c6 11.9 18.1 19.4 31.5 19.4h62.8a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7h161.1a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7H923c19.4 0 35.3-15.8 35.3-35.3a35.42 35.42 0 0 0-35.4-35.2zM305.7 253l575.8 1.9-56.4 315.8-452.3.8L305.7 253zm96.9 612.7c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6zm325.1 0c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6z">
                                        </path>
                                    </svg> অর্ডার করুন</a><a
                                    href="tel:{{ get_setting('contact_phone') }}">{{ get_setting('contact_phone') }}</a>
                                <h3>অর্ডার পেতে কল করুন এই নাম্বারে</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="section_gaps"></div>
            <div id="CustomerReview" class="CustomerReview">
                <section id="CustomerReviewContent" class="customer-review_CustomerReviewContent__QAt_k">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <h2>আমাদের কাস্টমার রিভিউ</h2>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div id="CustomerReviewImg" class="customer-review_CustomerReviewImg__1Fuey"><img
                                        src="{{ url('public/landing-pages/images/customer-review/customer-review1.png') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div id="CustomerReviewImg" class="customer-review_CustomerReviewImg__1Fuey"><img
                                        src="{{ url('public/landing-pages/images/customer-review/customer-review2.png') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div id="CustomerReviewImg" class="customer-review_CustomerReviewImg__1Fuey"><img
                                        src="{{ url('public/landing-pages/images/customer-review/customer-review3.png') }}"
                                        alt="" /></div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <div id="CustomerReviewImg" class="customer-review_CustomerReviewImg__1Fuey"><img
                                        src="{{ url('public/landing-pages/images/customer-review/customer-review1.png') }}"
                                        alt="" /></div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <section id="placeAnOrder">
                <section id="OrderConfirmFrom" class="order_OrderConfirmFrom__eiWmc">
                    <div class="container">
                        <form action="{{ route('landing-pages.order_landing_page', $landingPage->slug) }}"
                            method="POST">
                            @csrf
                            <div class="row">
                                <h2>তাই আর দেরি না করে আজই অর্ডার করুন </h2>
                                <div class="col-lg-7">
                                    <div id="OrderConfirmLeft" class="order_OrderConfirmLeft__HZHqT">
                                        <h3>Billing details</h3>
                                        <div id="CustomeInput" class="order_CustomeInput__k6j_b">
                                            <input type="text" name="name" placeholder="আপনার নাম লিখুন *"
                                                required />
                                        </div>
                                        <div id="CustomeInput" class="order_CustomeInput__k6j_b">
                                            <input type="text" name="mobile"
                                                placeholder="আপনার মোবাইল নাম্বার লিখুন *" required />
                                        </div>
                                        <div id="CustomeInput" class="order_CustomeInput__k6j_b">
                                            <input type="text" name="address"
                                                placeholder="আপনার সম্পূর্ণ ঠিকানা লিখুন *" required />
                                        </div>


                                        <div class="row mt-3" id="payment_div">
                                            <div class="col-12">
                                                <h3 class="my-2">Payment By</h3>
                                            </div>

                                            @if (get_setting('bkash') == 1)
                                                <div class="col-6 col-md-4">
                                                    <label class="aiz-megabox d-block mb-3 border rounded">
                                                        <input value="bkash" class="online_payment" type="radio"
                                                            name="payment_option" checked="">
                                                        <span class="d-block aiz-megabox-elem p-3">
                                                            <img src="{{ url('public/assets/img/cards/bkash.png') }}"
                                                                class="img-fluid mb-2">
                                                            <span class="d-block text-center">
                                                                <span class="d-block fw-bold fs-15">Bkash</span>
                                                            </span>
                                                        </span>
                                                    </label>
                                                </div>
                                            @endif
                                            @if (get_setting('nagad') == 1)
                                                <div class="col-6 col-md-4">
                                                    <label class="aiz-megabox d-block mb-3 border rounded">
                                                        <input value="nagad" class="online_payment" type="radio"
                                                            name="payment_option" checked="">
                                                        <span class="d-block aiz-megabox-elem p-3">
                                                            <img src="{{ url('public/assets/img/cards/nagad.png') }}"
                                                                class="img-fluid mb-2">
                                                            <span class="d-block text-center">
                                                                <span class="d-block fw-bold fs-15">Nagad</span>
                                                            </span>
                                                        </span>
                                                    </label>
                                                </div>
                                            @endif
                                            @if (get_setting('paypal_payment') == 1)
                                                <div class="col-6 col-md-4">
                                                    <label class="aiz-megabox d-block mb-3 border rounded">
                                                        <input value="paypal" class="online_payment" type="radio"
                                                            name="payment_option" checked="">
                                                        <span class="d-block aiz-megabox-elem p-3">
                                                            <img src="{{ url('public/assets/img/cards/paypal.png') }}"
                                                                class="img-fluid mb-2">
                                                            <span class="d-block text-center">
                                                                <span class="d-block fw-bold fs-15">Paypal</span>
                                                            </span>
                                                        </span>
                                                    </label>
                                                </div>
                                            @endif
                                            @if (get_setting('cash_payment'))
                                                <div class="col-6 col-md-4">
                                                    <label class="aiz-megabox d-block mb-3 border rounded">
                                                        <input value="cash_on_delivery" class="online_payment"
                                                            type="radio" name="payment_option" checked="">
                                                        <span class="d-block aiz-megabox-elem p-3">
                                                            <img src="{{ url('public/assets/img/cards/cod.png') }}"
                                                                class="img-fluid mb-2">
                                                            <span class="d-block text-center">
                                                                <span class="d-block fw-bold fs-15">Cash On
                                                                    Delivery</span>
                                                            </span>
                                                        </span>
                                                    </label>
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-5">
                                    <div id="OrderConfirmRight" class="order_OrderConfirmRight__9BH89">
                                        <h3>Your order</h3>
                                        <ul>
                                            <li>
                                                <h4>Product</h4>
                                                <h5>Subtotal</h5>
                                            </li>
                                            <li>
                                                <div id="left" class="order_left__HNlRT order_d_flex__P2VQu">
                                                    <div id="img" class="order_img__nMxcc">
                                                        @if ($landingPage->product->thumbnail)
                                                            <img src="{{ url('public/' . $landingPage->product->thumbnail->file_name) }}"
                                                                alt="{{ $landingPage->product->name }}" />
                                                        @endif
                                                    </div>
                                                    <p>{{ $landingPage->product->name }}</p>
                                                </div>
                                                <div id="right" class="order_right__uO4sF order_d_flex__P2VQu">
                                                    <input type="hidden" name="product_id"
                                                        value="{{ $landingPage->product->id }}" />
                                                    <input type="number" id="quantity" name="quantity"
                                                        value="1" required />
                                                    <h5> ৳ {{ $landingPage->product->unit_price }}</h5>
                                                </div>
                                            </li>
                                            <li>
                                                <h5>Subtotal</h5>
                                                <h5>৳ <span
                                                        id="subtotal">{{ $landingPage->product->unit_price }}</span>
                                                </h5>
                                            </li>
                                            <li>
                                                <h5>Shipping</h5>
                                                <h5>
                                                    <div id="checkbox1"
                                                        class="order_checkbox__TScFd order_d_flex__P2VQu">
                                                        <input type="radio" id="Inside" name="shipping"
                                                            value="{{ $landingPage->inside_dhaka }}" checked />
                                                        <label for="Inside">Inside Dhaka : ৳
                                                            {{ $landingPage->inside_dhaka }}</label>
                                                    </div>
                                                    <div id="checkbox2"
                                                        class="order_checkbox__TScFd order_d_flex__P2VQu">
                                                        <input type="radio" id="Outside" name="shipping"
                                                            value="{{ $landingPage->outside_dhaka }}" />
                                                        <label for="Outside">Outside Dhaka: ৳
                                                            {{ $landingPage->outside_dhaka }}</label>
                                                    </div>

                                                </h5>
                                            </li>
                                            <li>
                                                <h4>Total</h4>
                                                <h4>৳ <span
                                                        id="total">{{ $landingPage->product->unit_price }}</span>
                                                </h4>
                                            </li>
                                        </ul><button> <svg stroke="currentColor" fill="currentColor" stroke-width="0"
                                                viewBox="0 0 24 24" height="1em" width="1em"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path
                                                    d="M4.00436 6.41662L0.761719 3.17398L2.17593 1.75977L5.41857 5.00241H20.6603C21.2126 5.00241 21.6603 5.45012 21.6603 6.00241C21.6603 6.09973 21.6461 6.19653 21.6182 6.28975L19.2182 14.2898C19.0913 14.7127 18.7019 15.0024 18.2603 15.0024H6.00436V17.0024H17.0044V19.0024H5.00436C4.45207 19.0024 4.00436 18.5547 4.00436 18.0024V6.41662ZM6.00436 7.00241V13.0024H17.5163L19.3163 7.00241H6.00436ZM5.50436 23.0024C4.67593 23.0024 4.00436 22.3308 4.00436 21.5024C4.00436 20.674 4.67593 20.0024 5.50436 20.0024C6.33279 20.0024 7.00436 20.674 7.00436 21.5024C7.00436 22.3308 6.33279 23.0024 5.50436 23.0024ZM17.5044 23.0024C16.6759 23.0024 16.0044 22.3308 16.0044 21.5024C16.0044 20.674 16.6759 20.0024 17.5044 20.0024C18.3328 20.0024 19.0044 20.674 19.0044 21.5024C19.0044 22.3308 18.3328 23.0024 17.5044 23.0024Z">
                                                </path>
                                            </svg> Place Order BDT
                                            <span id="orderTotal">{{ $landingPage->product->unit_price }}</button>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </section>
            </section>
            <div class="footer4_Footer4__v948q">
                <section class="footer4_Footer4Sec__Xz0We">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <div class="footer4_FooterMainDiv__uWQWn">
                                    <div class="footer4_FooterMainDiv1__i4BvN"><a href="landing-3.html#">
                                            <h4> <svg stroke="currentColor" fill="currentColor" stroke-width="0"
                                                    viewBox="0 0 24 24" height="1em" width="1em"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path fill="none" d="M0 0h24v24H0z"></path>
                                                    <path
                                                        d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5a2.5 2.5 0 010-5 2.5 2.5 0 010 5z">
                                                    </path>
                                                </svg> Kuril, Vatara, Dhaka-1229, Bangladesh</h4>
                                        </a></div>
                                    <div class="footer4_FooterMainDiv2__wjIT7"><a href="landing-3.html">
                                            <h4> Privacy Policy</h4>
                                        </a><a href="landing-3.html">
                                            <h4> Terms &amp; Conditions</h4>
                                        </a></div>
                                </div>
                                <div id="tinyFooter2" class="footer4_tinyFooter2__F01lH">
                                    <div class="footer4_Hr__iD0vj"></div>
                                    <div>
                                        <p>© 2024 All Rights Reserved Designed by <a href="https://zo.tc/">Zo.Tc</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script id="__NEXT_DATA__"
        type="application/json">{"props":{"pageProps":{}},"page":"/landing-3","query":{},"buildId":"8ZCiJa4AZL4bT4qhWltbh","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script>

    <script>
        $(document).ready(function() {
            function calculateTotal() {
                var quantity = parseInt($('#quantity').val());
                if (quantity < 1) {
                    $('#quantity').val(1);
                    quantity = 1;
                }

                var product_price = parseFloat('{{ $landingPage->product->unit_price }}');

                var subtotal = quantity * product_price;
                $('#subtotal').html(subtotal);

                var shippingCost = parseFloat($('input[name="shipping"]:checked').val());

                var total = subtotal + shippingCost;
                $('#total, #orderTotal').html(total);
            }

            calculateTotal();

            $('#quantity, input[name="shipping"]').change(function() {
                calculateTotal();
            });

            $('#CashOn').change(function() {
                if ($(this).prop('checked')) {
                    $('#payment_div').slideUp();
                } else {
                    $('#payment_div').slideDown();
                }
            });

        });
    </script>
</body>

</html>
